# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# allows you to type Bash style comments on your command line
setopt interactivecomments

# EDITOR
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
export NVM_LAZY_LOAD=true

plugins=(
  sudo svn git git-extras colored-man-pages web-search wd npm gem extract common-aliases taskwarrior k
  pip python postgres gulp docker composer wp-cli aws heroku zsh-nvm virtualenv
  zsh-autosuggestions zsh-syntax-highlighting
)

# User configuration

# eval "$(hub alias -s)"
# eval "$(rbenv init - --no-rehash zsh)"
# eval "$(pyenv init -)"
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

### Tmux
export TERM=xterm-256color

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LC_ALL=fr_FR.UTF-8
export LANG=fr_FR.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[[ -r $NVM_DIR/bash_completion ]] && \. $NVM_DIR/bash_completion

fpath=(/usr/local/share/zsh-completions $fpath)

# For LESS highlight
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS=" -R "

################################################################################
#                           START OWN ALIAS                                    #
################################################################################

# Unalias
# unalias rm

# Configuration files
alias vhosts='sudo $EDITOR /etc/hosts'
alias vimrc='$EDITOR ~/.vimrc'
alias tmux.conf='$EDITOR ~/.tmux.conf'
alias http.conf='sudo $EDITOR /etc/apache2/httpd.conf'
alias php.ini='$EDITOR /usr/local/etc/php/5.6/php.ini'

# Directory
alias tmp='cd $TMPDIR'

# Applications
alias git='LC_ALL=en_GB git'
alias issues='hub browse -- issues'
alias my-issues='hub issue -a $USER'
alias pull-request='hub browse -- pulls'
alias psqlConnect='PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER -h $DATABASE_HOST $DATABASE_NAME'

# Software
alias tmuxdev='tmux new -s dev'
alias mytmux='tmux new -s mine'
alias vims='vim -p'
alias viml='vim -S' # load vim session
alias diff='vim -d'
alias cat='bat'
alias youtube='mpsyt'
alias fileManager='ranger'
alias calendar='cal'
alias serverHTTP='python -m SimpleHTTPServer'
alias cppCompile='c++ -std=c++11 -stdlib=libc++'
alias format='fmt'
alias spotlight='spot'
alias weather='curl wttr.in'
alias less='less -m -g -i -J --underline-special --SILENT'
alias tscp='tsc -p tsconfig.json'

# Git alias
alias master='git checkout master'
alias develop='git checkout develop'
alias branch='git checkout'

# Utilities
alias untracked='svn st | grep ?'
kcopy() {
  cat $1 | pbcopy
}

################################################################################
#                             END OWN ALIAS                                    #
################################################################################
